events {
    worker_connections 1024;
}

http {
  upstream api-gateway {
    least_conn;
    server api-gateway1:8080;
    server api-gateway2:8080;
    # server api-gateway3:8080;
    # server api-gateway4:8080;
  }

  server {
    listen 8080;

    location / {
      proxy_pass http://api-gateway;
    }

  }
}
