services:

  # Les fichiers d'initialisation des modules sont collectés localement
  copie-initdb-services:
    image: alpine
    volumes:
      - ./db-init:/data
      - ./db-scripts:/scripts
      - ./svc-clients/db-init:/db_clients
      - ./svc-commandes/db-init:/db_commandes
      - ./svc-facturation/db-init:/db_facturation
      - ./svc-facturation/init-scripts:/scripts_facturation
      - ./svc-catalogue/init-scripts:/scripts_catalogue
    command: >
      sh -c "cp /db_clients/init.sql /data/init-clients.sql;
            cp /db_commandes/init.sql /data/init-commandes.sql;
            cp /db_facturation/init.sql /data/init-facturation.sql;
            cp /scripts_catalogue/*.js /scripts/;
            cp /scripts_facturation/*.js /scripts/;"

  mysql:
    image: mysql:8.4.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: cantelcox
      MYSQL_PASSWORD: RXc9HsR1wuKL7z2sgTd7S1
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    networks:
      - cantelcox-network
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 1s

  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_cantelcox
      MONGO_INITDB_ROOT_PASSWORD: cantelcox
      MONGO_INITDB_DATABASE: cantelcox
    volumes:
      - mongo_data:/data/db
      - ./db-scripts:/docker-entrypoint-initdb.d
    networks:
      - cantelcox-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping').ok", "--quiet"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7
    restart: unless-stopped
    networks:
      - cantelcox-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s

  krakend:
    image: devopsfaith/krakend:2.7
    restart: unless-stopped
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./config/krakend.json:/etc/krakend/krakend.json
    networks:
      - cantelcox-network
    depends_on:
      - svc_clients
      - svc_orchestration
      - svc_commandes
      - jaeger
      - keycloak

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - "9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - cantelcox-network
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    environment:
      - GF_LOG_LEVEL=debug
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - cantelcox-network
    depends_on:
      - prometheus

  postgres_kc:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=cantelcox
      - POSTGRES_USER=keycloak
    networks:
      - cantelcox-network

include:
  - svc-orchestration/docker-compose.yml
  - svc-clients/docker-compose.yml
  - svc-commandes/docker-compose.yml
  - svc-catalogue/docker-compose.yml
  - svc-facturation/docker-compose.yml
  - svc-lignes/docker-compose.yml

networks:
  cantelcox-network:
    external: true

volumes:
  mysql_data:
  mongo_data:
  postgres_data:
  prometheus_data:
  grafana_data: