@startuml
skinparam componentStyle uml2
skinparam backgroundColor #F5F9F5
skinparam defaultFontName Arial

skinparam package {
    BackgroundColor White
    BorderColor #2D6A8E
    BorderThickness 1.5
    FontStyle bold
}

skinparam component {
    BackgroundColor White
    BorderColor #2D6A8E
    BorderThickness 1
}

skinparam arrowColor #9E2A3A

skinparam linetype polyline

title Architecture Hexagonale - svc-catalogue

package "Adapteurs d'entrée" as AdapteurE  {
    component "API REST (Flask)\n(HTTP)" as WebController
    component "Kafka Consumer\n(Messaging)" as EventConsumer
}

package "Application" as App {
    component "CreateProductOffering\nUseCase" as CreatePOUC
    component "DeleteProductOffering\nUseCase" as DeletePOUC
    component "GetProductOfferings\nUseCase" as GetPOUC
    component "UpdateStock\nUseCase" as UpdateStockUC
}

package "Domaine (cœur pur)" as Domaine #D5E8D4 {
    component "ProductOffering" as ProductOffering
    component "ProductOfferingState" as POState
    
    ProductOffering *-- POState
}

package "Adapters de sortie" as AdaptesO {
    component "Mongo DAO Adapter\n(MongoDB Persistence)" as MongoAdapter
    component "SQL Outbox Adapter\n(SQLAlchemy Outbox)" as SQLOutbox
    component "Kafka Publisher\n(kafka_producer)" as KafkaPublisher
}

' --- Relations Adapteurs In (Synchrone) -> App ---
WebController --> CreatePOUC : POST /productofferings
WebController --> DeletePOUC : DELETE /productofferings
WebController --> GetPOUC : GET /productofferings
WebController --> UpdateStockUC : POST /stock (Mise à jour manuelle)

' --- Relations Adapteurs In (Événementiel) -> App ---
EventConsumer --> UpdateStockUC : OrderDraft\n(Réserve le stock)
EventConsumer --> UpdateStockUC : OrderCreated\n(Confirme la baisse de stock)
EventConsumer --> UpdateStockUC : OrderCancelled\n(Restaure le stock)

' --- Relations App -> Domaine ---
CreatePOUC .down.> ProductOffering 
DeletePOUC .down.> ProductOffering 
GetPOUC .down.> ProductOffering
UpdateStockUC .down.> ProductOffering 

' --- Relations App -> Adapteurs de sortie ---
CreatePOUC --> MongoAdapter 
DeletePOUC --> MongoAdapter 
GetPOUC --> MongoAdapter 
UpdateStockUC --> MongoAdapter 

UpdateStockUC --> SQLOutbox : Sauvegarde Événement (Outbox)
UpdateStockUC --> KafkaPublisher : Publie événements métier

@enduml
