@startuml
title
Diagramme de cas d'utilisation
endtitle
header CanTelcoX - DEGV03078209 - ÉTS - LOG430 - E26
top to bottom direction

package Usagers {
usecase "UC-01 – Inscription &\nvérification d'identité" as UC1
usecase "UC-04 – Consultation de \nl'usage et des factures" as UC4
usecase "UC-05 – Prise de commande /\nsouscription à un forfait" as UC5
usecase "UC-06 – Paiement de facture mobile" as UC6
}
package Système {
usecase "UC-03 – Activation d'une ligne mobile" as UC3
usecase "UC-08 – Cycle de\nfacturation mensuel" as UC8
}

package "Sécurité et audit" {
usecase "UC-02 – Authentification & MFA" as UC2
usecase "UC-07 – Détection de fraude" as UC7
}
Abonné --> UC1
Usagers --> UC2 : <<utilise>>
Abonné --> UC4
Abonné --> UC5
Abonné --> UC6
UC5 --> UC3 : <<utilise>>
UC1 --> UC7 : <<utilise>>
UC5 --> UC7 : <<utilise>>

Opérateur -up-> UC8
Régulateur -up-> UC7
@enduml
