@startnwdiag
title
Diagramme de réseau - Déploiement en test
endtitle
header CanTelcoX - DEGV03078209 - ÉTS - LOG430 - E26
nwdiag {
    network WAN {
        group {
            description = "Accès public"
            color = #TECHNOLOGY
            api-gateway [address = "localhost:8080"]
            keycloak [address = "localhost:8081"]
        }
        group {
            description = "Intranet"
            color = #APPLICATION
            udm [address = "localhost:8000"]
            webui [address = "localhost:5050"]
            grafana [address = "localhost:3000"]
            jaeger [address = "localhost:16686"]
            usage-api [address = "localhost:8090"]
        }
        group {
            description = "Accès aux bases de données"
            color = #IMPLEMENTATION
            mysql [address = "localhost:3306"]
            mongo [address = "localhost:27017"]
            mongo-free5gc [address = "localhost:27018"]
            redis [address = "localhost:6379"]
            postgres_kc [address = "localhost:5432"]
        }
        group {
            description = "Test avec Postman"
            color = #IMPLEMENTATION
            svc_client [address = "localhost:5001"]
            svc_facturation [address = "localhost:5005"]
            svc_commandes [address = "localhost:5002"]
            svc_catalogue [address = "localhost:5003"]
            svc_orchestration [address = "localhost:5123"]
        }
    }
    network cantelcox-network {
        api-gateway [address = "api-gateway:8080"]
        mysql [address = "mysql:3306"]
        mongo [address = "mongo:27017"]
        redis [address = "redis:6379"]
        prometheus [address = "prometheus:9090"]
        grafana [address = "grafana:3000"]
        postgres_kc [address = "postgres_kc:5432"]
        mysql [address = "mysql:3306"]
        usage-api [address = "webui:8080"]
        svc_orchestration [address = "svc_orchestration:5123"]
        svc_facturation [address = "svc_facturation:5000"]
        svc_client [address = "svc_client:5000"]
        keycloak [address = "keycloak:8080"]
        svc_commandes [address = "svc_commandes:5000"]
        svc_catalogue [address = "svc_catalogue:5000"]
        jaeger [address = "jaeger:16686\njaeger:4317\n..."]
    }
    network privnet {
        mongo-free5gc [address = "mongo-free5gc:27017"]
        nrf [address = "nrf:8000"]
        udr [address = "udr:8000"]
        udm [address = "udm:8000"]
        webui [address = "webui:5000"]
    }
}
@endnwdiag
