-- Script pour générer des données de test pour customerbills et billlines
-- Génère 100 customerbills avec partyRef=2 et billcycle_id=1
-- Chaque customerbill a entre 1 et 10 billlines associées

USE customerbills;

-- Désactiver temporairement les vérifications de clés étrangères pour accélérer l'insertion
SET FOREIGN_KEY_CHECKS = 0;

-- Générer 100 customerbills
INSERT INTO customerbills (id, partyRef, billcycle_id, bill_date, next_bill_date, remaining_amount, bill_status, payment_link) VALUES
(1, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(2, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(3, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(4, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(5, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(6, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(7, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(8, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(9, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(10, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(11, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(12, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(13, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(14, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(15, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(16, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(17, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(18, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(19, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(20, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(21, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(22, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(23, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(24, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(25, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(26, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(27, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(28, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(29, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(30, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(31, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(32, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(33, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(34, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(35, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(36, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(37, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(38, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(39, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(40, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(41, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(42, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(43, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(44, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(45, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(46, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(47, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(48, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(49, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(50, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(51, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(52, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(53, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(54, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(55, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(56, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(57, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(58, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(59, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(60, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(61, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(62, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(63, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(64, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(65, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(66, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(67, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(68, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(69, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(70, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(71, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(72, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(73, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(74, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(75, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(76, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(77, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(78, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(79, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(80, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(81, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(82, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(83, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(84, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(85, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(86, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(87, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(88, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(89, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(90, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(91, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(92, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(93, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(94, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(95, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(96, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(97, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(98, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(99, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000))),
(100, 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), ROUND(RAND() * 1000, 2), ELT(FLOOR(1 + RAND() * 3), 'DUE', 'PAID', 'CANCELED'), CONCAT('payment-link-', FLOOR(1 + RAND() * 1000)));

-- Générer des billlines pour chaque customerbill (entre 1 et 10 par customerbill)
DELIMITER //
CREATE PROCEDURE generate_billlines()
BEGIN
    DECLARE i INT DEFAULT 1;
    DECLARE num_lines INT;
    DECLARE bill_id INT;

    WHILE i <= 100 DO
        -- Générer entre 1 et 10 lignes par facture
        SET num_lines = FLOOR(1 + RAND() * 10);
        SET bill_id = i;

        WHILE num_lines > 0 DO
            INSERT INTO billlines (customerbill_id, productRef, usageRef, amount) VALUES
            (bill_id, FLOOR(1 + RAND() * 100),
             CONCAT('USG-', FLOOR(1000 + RAND() * 9000)),
             ROUND(RAND() * 100, 2));
            SET num_lines = num_lines - 1;
        END WHILE;

        SET i = i + 1;
    END WHILE;
END //
DELIMITER ;

-- Exécuter la procédure pour générer les billlines
CALL generate_billlines();

-- Supprimer la procédure après utilisation
DROP PROCEDURE IF EXISTS generate_billlines;

-- Réactiver les vérifications de clés étrangères
SET FOREIGN_KEY_CHECKS = 1;

-- Afficher un résumé
SELECT 'customerbills' AS table_name, COUNT(*) AS row_count FROM customerbills
UNION ALL
SELECT 'billlines' AS table_name, COUNT(*) AS row_count FROM billlines;